--- #YAML:1.0
name:               Net-Ident
version:            1.22
abstract:           Lookup the username on the remote end of a TCP/IP connection
author:
    - Jan-Pieter Cornet <johnpc@xs4all.nl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    IO::Socket:           ~
requires:
    Carp:        0
    Config:      0
    Exporter:    0
    Fcntl:       0
    FileHandle:  0
    Socket:      0
    vars:        0
resources:
    homepage:    http://wiki.github.com/toddr/Net-Ident/
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/Net-Ident
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
